name: redis

on: workflow_dispatch

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - upstream_version: "6.1"
          - upstream_version: "6.2"
          - upstream_version: "7.4"
          - upstream_version: "8.0"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to aliyun
        uses: docker/login-action@v3
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUNCR_USERNAME }}
          password: ${{ secrets.ALIYUNCR_PASSWORD }}
      - name: Build and push to aliyun
        uses: docker/build-push-action@v5
        with:
          push: true
          context: "{{defaultContext}}:drupal"
          platforms: linux/amd64,linux/arm64
          file: "Dockerfile.template"
          tags: "registry.cn-hangzhou.aliyuncs.com/davyin/redis:${{ matrix.version.upstream_version }}"
          build-args: |
            UPSTREAM_VERSION=${{ matrix.version.upstream_version }}